### ISSUE TITLE
Remove MPGGE calculations from simdrive

### ISSUE THREAD

**Issue by jakeholden** [NREL/fastsim#2]
Performing mpgge calculations under-the-hood leads to problems especially with diesel powertrains. Remove mpgge and force users to explicitly sum the fuel storage energy out array and multiply by their lower heating value of choice to get a fuel volume or mass.

**Comment by kylecarow** [comment]
Closing, in FASTSim-3 we will just use SI units internally and perhaps have convenience functions for things like mpg (with mandatory LHV parameter and perhaps density)
