### ISSUE TITLE
IsDefault

### ISSUE THREAD

**Issue by calbaker** [NREL/fastsim#60]
The goal is so that we can write rust objects to file without writing out a bunch of boilerplate stuff that will pretty much always be the same. 

Make this trait and use it to decide whether to serialize fields.  It should look about like this:
```rust
pub trait IsDefault<T: Default + PartalCmp> {
    fn is_default(&self) -> bool {
        Self == Self::default()
    }
}
```

and decorate appropriate struct fields with something like
```rust
// It's possible these next two lines can be combined
#[serde(skip_serializing_if::IsDefault::is_default)]
#[serde(default)]
```

**Comment by calbaker** [comment]
@robinsteuteville, see if you can figure this out with a fresh branch off `fastsim-2` if you run out of stuff to do.

**Comment by kylecarow** [comment]
This exists in FASTSim 3. Chad says this probably doesnt matter in FASTSim 2, because it won't affect how much gets serialized
